# Generated by Django 5.0.1 on 2024-01-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('Event_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Number_of_Volunteer', models.PositiveIntegerField(verbose_name='Number of Volunteers')),
                ('Size_of_Event', models.PositiveIntegerField(verbose_name='Size of Event')),
                ('Event_Name', models.CharField(max_length=20, verbose_name='Event Name')),
                ('Location', models.CharField(max_length=20, verbose_name='Location')),
                ('Event_Status', models.IntegerField(choices=[(1, 'Past'), (0, 'Coming')], default=0)),
            ],
        ),
    ]
