# Generated by Django 5.0.1 on 2024-01-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
        ('Volunteer', '0002_rename_age_volunteer_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='Volunteers',
            field=models.ManyToManyField(related_name='events', to='Volunteer.volunteer', verbose_name='Volunteers'),
        ),
        migrations.AlterField(
            model_name='events',
            name='Event_ID',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='Event_Status',
            field=models.CharField(choices=[('PAST', 'Past'), ('COMING', 'Coming')], default='PAST'),
        ),
    ]
