# Generated by Django 5.0.1 on 2024-01-18 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_events_volunteers_alter_events_event_id_and_more'),
        ('Volunteer', '0002_rename_age_volunteer_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='Volunteers',
        ),
        migrations.AddField(
            model_name='events',
            name='Volunteers',
            field=models.OneToOneField(default=199, on_delete=django.db.models.deletion.CASCADE, to='Volunteer.volunteer'),
            preserve_default=False,
        ),
    ]
