# Generated by Django 5.0.1 on 2024-01-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_remove_events_volunteers_events_volunteers'),
        ('Volunteer', '0002_rename_age_volunteer_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='Volunteers',
        ),
        migrations.AddField(
            model_name='events',
            name='Volunteers',
            field=models.ManyToManyField(related_name='events', to='Volunteer.volunteer', verbose_name='Volunteers'),
        ),
    ]
