# Generated by Django 5.0.1 on 2024-01-18 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_remove_events_volunteers_events_volunteers'),
        ('Organization', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='created_Org_By',
            field=models.OneToOneField(default=199, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='Organization.organization'),
            preserve_default=False,
        ),
    ]
