# Generated by Django 5.0.1 on 2024-01-18 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0005_events_created_org_by'),
        ('Organization', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='created_Org_By',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='Organization.organization'),
        ),
    ]
