# Generated by Django 5.0.1 on 2024-01-18 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0007_remove_events_volunteers'),
        ('Organization', '0004_organization_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='created_Org_By',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='Organization.organization'),
        ),
    ]
