# Generated by Django 5.0.1 on 2024-01-18 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0008_alter_events_created_org_by'),
        ('Organization', '0004_organization_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='Event_Date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='created_Org_By',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducting_Org', to='Organization.organization'),
        ),
    ]
