# Generated by Django 5.0.1 on 2024-01-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0009_events_event_date_alter_events_created_org_by'),
        ('Volunteer', '0004_volunteer_email_volunteer_is_volunteer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='created_Org_By',
            new_name='Created_Org',
        ),
        migrations.AddField(
            model_name='events',
            name='Reg_volunteers',
            field=models.ManyToManyField(blank=True, related_name='registered_events', to='Volunteer.volunteer'),
        ),
    ]
