# Generated by Django 5.0.1 on 2024-01-20 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0010_rename_created_org_by_events_created_org_and_more'),
        ('Volunteer', '0005_remove_volunteer_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='Event_Status',
            field=models.CharField(choices=[('PAST', 'Past'), ('COMING', 'Coming')], default='COMING'),
        ),
        migrations.CreateModel(
            name='Emp_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Register', models.BooleanField(default=False)),
                ('Event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.events', verbose_name='Record_Event')),
                ('Volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Volunteer.volunteer', verbose_name='Record_Volunteer')),
            ],
        ),
    ]
