# Generated by Django 5.0.1 on 2024-01-20 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0011_alter_events_event_status_emp_record'),
        ('Volunteer', '0005_remove_volunteer_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_record',
            name='Volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Volunteer.volunteer', verbose_name='Record_Volunteer'),
        ),
    ]
