# Generated by Django 5.0.1 on 2024-01-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Organization', '0002_delete_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('Org_ID', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('Org_Name', models.CharField(max_length=20)),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
