# Generated by Django 5.0.1 on 2024-01-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
