# Generated by Django 5.0.1 on 2024-01-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0004_organization_verify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='area',
        ),
        migrations.AddField(
            model_name='organization',
            name='Location_of',
            field=models.CharField(default=44, max_length=50),
            preserve_default=False,
        ),
    ]
