# Generated by Django 5.0.1 on 2024-01-18 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0006_organization_last_login_organization_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='password',
        ),
    ]
