# Generated by Django 5.0.1 on 2024-01-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('Volunteer_ID', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Others')])),
                ('age', models.IntegerField()),
                ('location', models.CharField(max_length=20)),
            ],
        ),
    ]
