# Generated by Django 5.0.1 on 2024-01-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Volunteer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='location',
            new_name='Location',
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='Gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHERS', 'Others')], max_length=6),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='Volunteer_ID',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
