# Generated by Django 5.0.1 on 2024-01-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Volunteer', '0002_rename_age_volunteer_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='password',
            field=models.CharField(default=12345678, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
