# Generated by Django 5.0.1 on 2024-01-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Volunteer', '0003_volunteer_last_login_volunteer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(default=122, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='is_volunteer',
            field=models.BooleanField(default=True),
        ),
    ]
