# Generated by Django 5.0.1 on 2024-01-18 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Volunteer', '0004_volunteer_email_volunteer_is_volunteer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='password',
        ),
    ]
