# Generated by Django 5.0.2 on 2024-03-02 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('Role', models.CharField(choices=[('Org', 'organization'), ('Vol', 'volunteer')], max_length=50)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('Org_ID', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('Org_Name', models.CharField(max_length=20)),
                ('Location', models.CharField(max_length=50)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='org_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('Event_ID', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('Event_Description', models.TextField()),
                ('Number_of_Volunteer', models.PositiveIntegerField(verbose_name='Number of Volunteers')),
                ('Size_of_Event', models.PositiveIntegerField(verbose_name='Size of Event')),
                ('Event_Name', models.CharField(max_length=20, verbose_name='Event Name')),
                ('Location', models.CharField(max_length=20, verbose_name='Location')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('Registration_option', models.BooleanField(default=True)),
                ('poster_url', models.TextField(blank=True, null=True)),
                ('Event_Date', models.DateTimeField(blank=True, null=True)),
                ('Event_Status', models.CharField(choices=[('PAST', 'Past'), ('COMING', 'Coming')], default='COMING', max_length=20)),
                ('Created_Org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducting_Org', to='base.org')),
            ],
        ),
        migrations.CreateModel(
            name='volunteer',
            fields=[
                ('Vol_ID', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=20)),
                ('Gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHERS', 'Others')], max_length=50)),
                ('Age', models.PositiveIntegerField()),
                ('Location', models.CharField(max_length=50)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='vol_profile/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vol_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='registered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='base.events')),
                ('vol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_vol', to='base.volunteer')),
            ],
        ),
    ]
