# Generated by Django 5.0.2 on 2024-03-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='Age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='Name',
            field=models.CharField(default='empty', max_length=20),
        ),
    ]
