# Generated by Django 5.0.1 on 2024-01-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='Age',
            field=models.PositiveIntegerField(),
        ),
    ]
