# Generated by Django 5.0.2 on 2024-02-11 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_org_remove_volunteer_id_alter_volunteer_vol_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('Role', models.CharField(choices=[('Org', 'organization'), ('Vol', 'volunteer')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='org',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='org',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='org',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='org',
            name='password',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='password',
        ),
        migrations.AddField(
            model_name='org',
            name='user',
            field=models.OneToOneField(default=22, on_delete=django.db.models.deletion.CASCADE, related_name='org_profile', to='base.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='user',
            field=models.OneToOneField(default=22, on_delete=django.db.models.deletion.CASCADE, related_name='vol_profile', to='base.user'),
            preserve_default=False,
        ),
    ]
