# Generated by Django 5.0.2 on 2024-02-11 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_reg_volunteers_event_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reg_Volunteers',
        ),
    ]
