# Generated by Django 5.0.2 on 2024-02-11 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_delete_reg_volunteers'),
    ]

    operations = [
        migrations.CreateModel(
            name='registered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='base.events')),
                ('vol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_vol', to='base.volunteer')),
            ],
        ),
    ]
