# Generated by Django 5.0 on 2024-02-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_verify_org_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='Event_disription',
            field=models.TextField(default='Test dicription', verbose_name='Event Discription'),
        ),
    ]
