# Generated by Django 5.0.2 on 2024-02-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_events_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='Event_Description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
