# Generated by Django 5.0.2 on 2024-02-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_events_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='Org_ID',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='Vol_ID',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
