# Generated by Django 5.0.2 on 2024-02-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_org_org_id_alter_volunteer_vol_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='poster_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
