# Generated by Django 5.0.2 on 2024-02-19 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_events_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='Event_disription',
        ),
    ]
